# Generated by Django 5.0.7 on 2024-07-14 16:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0003_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_description', ckeditor.fields.RichTextField(max_length=60000)),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.blog_category')),
            ],
        ),
    ]
