# Generated by Django 5.1 on 2024-08-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0003_headermain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subheader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_header', models.CharField(max_length=100)),
                ('main_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.headermain')),
            ],
        ),
    ]
