# Generated by Django 5.0.6 on 2024-07-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0006_college_model_course_model_course_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('Top Ranked Colleges', 'Top Ranked Colleges'), ('Popular Courses', 'Popular Courses'), ('Popular Specialization', 'Popular Specialization'), ('Colleges By Location', 'Colleges By Location'), ('Compare Colleges', 'Compare Colleges'), ('College Reviews', 'College Reviews'), ('Exams', 'Exams'), ('College Predictors', 'College Predictors'), ('Ask Current Students', 'Ask Current Students'), ('Rank Predictors', 'Rank Predictors'), ('Resources', 'Resources'), ('CAT Percentile Predictor', 'CAT Percentile Predictor')], default='Top Ranked Colleges', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.course_collection')),
            ],
            options={
                'verbose_name': 'Sub Collection',
                'verbose_name_plural': 'Sub Collections',
            },
        ),
    ]
