# Generated by Django 5.1 on 2024-08-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0006_headerdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerdetails',
            options={},
        ),
    ]
