# Generated by Django 5.0.6 on 2024-07-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0007_sub_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.course_collection')),
                ('sub_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.sub_collection')),
            ],
            options={
                'verbose_name': 'Sub Collection Category',
                'verbose_name_plural': 'Sub Collection Categories',
            },
        ),
    ]
