# Generated by Django 5.1 on 2024-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0007_alter_headerdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_model',
            name='course_brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochure/'),
        ),
    ]
