# Generated by Django 5.0.6 on 2024-07-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0008_subcollectioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('videos', models.URLField(blank=True, null=True, unique=True)),
                ('more_details', models.TextField(blank=True, null=True)),
                ('sub_collection_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.subcollectioncategory')),
            ],
            options={
                'verbose_name': 'Details Model',
                'verbose_name_plural': 'Details Models',
            },
        ),
    ]
