# Generated by Django 5.1 on 2024-08-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0008_college_model_course_brochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
