# Generated by Django 5.1 on 2024-08-26 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
