# Generated by Django 5.1 on 2024-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0010_notification_notification_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
