# Generated by Django 5.0.6 on 2024-07-30 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0010_exammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Overview', 'Overview'), ('Question Papers', 'Question Papers'), ('Date', 'Date'), ('Results', 'Results'), ('Cut Off', 'Cut Off'), ('Answer Key', 'Answer Key'), ('Analysis', 'Analysis'), ('Admit Card', 'Admit Card'), ('Center', 'Center'), ('Syllabus', 'Syllabus'), ('Mock Test', 'Mock Test')], default='Overview', max_length=50)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.exammodel')),
            ],
        ),
    ]
