# Generated by Django 5.0.6 on 2024-07-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0011_examcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('videos', models.URLField(blank=True, null=True, unique=True)),
                ('exam_image', models.ImageField(blank=True, null=True, upload_to='exam_image/')),
                ('sample_papers', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('guide', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochure/')),
                ('more_details', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.examcategory')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.exammodel')),
            ],
            options={
                'verbose_name_plural': 'Exam Details',
            },
        ),
    ]
