# Generated by Django 5.0.6 on 2024-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0012_examdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='status',
            field=models.BooleanField(default=False, help_text='0-default,1-Hidden'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='status',
            field=models.BooleanField(default=False, help_text='0-default,1-Hidden'),
        ),
    ]
