# Generated by Django 5.1 on 2024-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0012_course_model_eligibility_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_model',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
