# Generated by Django 5.0.6 on 2024-07-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0014_enquirymodel_alter_college_model_college_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetails',
            name='category',
        ),
    ]
