# Generated by Django 5.1 on 2024-08-30 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0015_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcolleges',
            name='college_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='college_logos/'),
            preserve_default=False,
        ),
    ]
