# Generated by Django 5.1 on 2024-09-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0017_applicationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='student_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('online', 'Online'), ('on-campus', 'On-campus')], max_length=50),
        ),
    ]
