# Generated by Django 3.0.5 on 2024-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0018_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
