# Generated by Django 5.1 on 2024-09-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0020_application_model_delete_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_model',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
