# Generated by Django 5.1 on 2024-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0021_college_model_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_model',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
