# Generated by Django 5.1 on 2024-09-12 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0022_college_model_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_model',
            name='place_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='place_image/'),
            preserve_default=False,
        ),
    ]
