# Generated by Django 3.2.10 on 2024-09-22 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0024_remove_application_model_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_model',
            name='header_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='header_image/'),
            preserve_default=False,
        ),
    ]
