# Generated by Django 3.2.10 on 2024-09-22 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0026_headerdetails_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on_course',
            name='header_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='header_image/'),
            preserve_default=False,
        ),
    ]
