# Generated by Django 3.2.10 on 2024-09-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0028_blog_details_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_image', models.ImageField(upload_to='images/')),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
            ],
        ),
    ]
