# Generated by Django 3.2.10 on 2024-09-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0029_statecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('header_image', models.ImageField(upload_to='header_image/')),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(upload_to='college_logos/')),
                ('college_image', models.ImageField(upload_to='college_image/')),
                ('total_course', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('min_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('college_description', models.TextField()),
                ('youtube_videos', models.URLField(blank=True, null=True, unique=True)),
                ('college_brochure', models.FileField(blank=True, null=True, upload_to='brochure/')),
                ('course_brochure', models.FileField(blank=True, null=True, upload_to='brochure/')),
                ('more_details', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.statecategory')),
            ],
        ),
    ]
