# Generated by Django 3.2.10 on 2024-09-23 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0030_collegemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='bsi_app.collegemodel'),
        ),
    ]
