# Generated by Django 3.2.10 on 2024-09-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0031_alter_course_model_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.collegemodel'),
        ),
    ]
