# Generated by Django 3.2.10 on 2024-09-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0032_alter_newslettersubscription_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcolleges',
            name='college_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_in', to='bsi_app.collegemodel'),
        ),
    ]
