# Generated by Django 3.2.10 on 2024-09-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0033_alter_featuredcolleges_college_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='header_image/')),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('course_brochure', models.FileField(blank=True, upload_to='brochure/')),
                ('course_details', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_on_courses', to='bsi_app.collegemodel')),
            ],
        ),
    ]
