# Generated by Django 3.2.10 on 2024-09-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0034_addoncourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_On_Course',
        ),
    ]
