# Generated by Django 3.2.10 on 2024-09-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0036_applicationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application_Model',
        ),
    ]
