# Generated by Django 5.0.7 on 2024-09-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0037_delete_application_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddOnCourse',
            new_name='AddOn_Course',
        ),
        migrations.RenameModel(
            old_name='EnquirySubmission',
            new_name='Enquiry_Submission',
        ),
        migrations.AlterField(
            model_name='enquiry_submission',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.collegemodel'),
        ),
    ]
