# Generated by Django 3.2.10 on 2024-09-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0037_delete_application_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquirySubmission',
        ),
    ]
