# Generated by Django 3.2.10 on 2024-09-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0037_delete_application_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirysubmission',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.collegemodel'),
        ),
    ]
