# Generated by Django 3.2.10 on 2024-09-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0038_rename_addoncourse_addon_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddOn_Course',
            new_name='AddOnCourse',
        ),
    ]
