# Generated by Django 3.2.10 on 2024-09-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0038_alter_enquirysubmission_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_model',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsi_app.collegemodel'),
        ),
        migrations.DeleteModel(
            name='College_Model',
        ),
    ]
