# Generated by Django 5.0.7 on 2024-09-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsi_app', '0039_enquiry_submission_enquirysubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquirySubmission',
        ),
    ]
